export const RETRIEVE_MOVIES_GENRES_SUCCESS = 'RETRIEVE_MOVIES_GENRES_SUCCESS';

export const RETRIEVE_POPULAR_MOVIES_SUCCESS = 'RETRIEVE_POPULAR_MOVIES_SUCCESS';
export const RETRIEVE_NOWPLAYING_MOVIES_SUCCESS = 'RETRIEVE_NOWPLAYING_MOVIES_SUCCESS';
export const RETRIEVE_MOVIES_LIST_SUCCESS = 'RETRIEVE_MOVIES_LIST_SUCCESS';
export const RETRIEVE_MOVIE_DETAILS_SUCCESS = 'RETRIEVE_MOVIE_DETAILS_SUCCESS';
export const RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS = 'RETRIEVE_MOVIES_SEARCH_RESULT_SUCCESS';

export const RETRIEVE_FISHING_REPORT_SUCCESS = 'RETRIEVE_FISHING_REPORT_SUCCESS';
export const RETRIEVE_WATERBODY_SUCCESS = 'RETRIEVE_WATERBODY_SUCCESS';

export const RETRIEVE_WEATHER_SUCCESS = "RETRIEVE_WEATHER_SUCCESS";

export const RETRIEVE_STOCKING_SUCCESS = "RETRIEVE_STOCKING_SUCCESS";

export const RETRIEVE_NOWPLAYING_SHOWS_SUCCESS = "RETRIEVE_NOWPLAYING_SHOWS_SUCCESS";
export const RETRIEVE_POPULAR_SHOWS_SUCCESS = 'RETRIEVE_POPULAR_SHOWS_SUCCESS';
export const RETRIEVE_SHOWS_LIST_SUCCESS = "RETRIEVE_SHOWS_LIST_SUCCESS";
